version: '3.8'
services:
  node1:
    build: .
    environment:
      - ID=1
      - HOST=node1
      - PORT=50051
      - PEERS=2:node2:50052,3:node3:50053
    networks:
      raft_net:
        aliases:
          - node1

  node2:
    build: .
    environment:
      - ID=2
      - HOST=node2
      - PORT=50052
      - PEERS=1:node1:50051,3:node3:50053
    networks:
      raft_net:
        aliases:
          - node2

  node3:
    build: .
    environment:
      - ID=3
      - HOST=node3
      - PORT=50053
      - PEERS=1:node1:50051,2:node2:50052
    networks:
      raft_net:
        aliases:
          - node3

networks:
  raft_net:
    driver: bridge
