# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"\x07\n\x05\x45mpty\"7\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\"8\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\"\x93\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x1a\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\t.LogEntry\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x05\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\":\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x11\n\toperation\x18\x03 \x01(\t\")\n\x14\x43lientRequestMessage\x12\x11\n\toperation\x18\x01 \x01(\t\"\'\n\x15\x43lientResponseMessage\x12\x0e\n\x06result\x18\x01 \x01(\t\"z\n\rStateResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\r\n\x05state\x18\x03 \x01(\t\x12\x13\n\x0b\x63ommitIndex\x18\x04 \x01(\x05\x12\x13\n\x0blastApplied\x18\x05 \x01(\x05\x12\x16\n\x03log\x18\x06 \x03(\x0b\x32\t.LogEntry2\xeb\x01\n\x0bRaftService\x12\x38\n\x0bRequestVote\x12\x13.RequestVoteRequest\x1a\x14.RequestVoteResponse\x12>\n\rAppendEntries\x12\x15.AppendEntriesRequest\x1a\x16.AppendEntriesResponse\x12>\n\rClientRequest\x12\x15.ClientRequestMessage\x1a\x16.ClientResponseMessage\x12\"\n\x08GetState\x12\x06.Empty\x1a\x0e.StateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=14
  _globals['_EMPTY']._serialized_end=21
  _globals['_REQUESTVOTEREQUEST']._serialized_start=23
  _globals['_REQUESTVOTEREQUEST']._serialized_end=78
  _globals['_REQUESTVOTERESPONSE']._serialized_start=80
  _globals['_REQUESTVOTERESPONSE']._serialized_end=136
  _globals['_APPENDENTRIESREQUEST']._serialized_start=139
  _globals['_APPENDENTRIESREQUEST']._serialized_end=286
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=288
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=342
  _globals['_LOGENTRY']._serialized_start=344
  _globals['_LOGENTRY']._serialized_end=402
  _globals['_CLIENTREQUESTMESSAGE']._serialized_start=404
  _globals['_CLIENTREQUESTMESSAGE']._serialized_end=445
  _globals['_CLIENTRESPONSEMESSAGE']._serialized_start=447
  _globals['_CLIENTRESPONSEMESSAGE']._serialized_end=486
  _globals['_STATERESPONSE']._serialized_start=488
  _globals['_STATERESPONSE']._serialized_end=610
  _globals['_RAFTSERVICE']._serialized_start=613
  _globals['_RAFTSERVICE']._serialized_end=848
# @@protoc_insertion_point(module_scope)
