# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"b\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"8\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\"\x98\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x1f\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x05\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\":\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x11\n\toperation\x18\x03 \x01(\t\")\n\x14\x43lientRequestMessage\x12\x11\n\toperation\x18\x01 \x01(\t\"8\n\x15\x43lientResponseMessage\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"\x13\n\x11LeaderInfoRequest\"=\n\x12LeaderInfoResponse\x12\x10\n\x08leaderId\x18\x01 \x01(\x05\x12\x15\n\rleaderAddress\x18\x02 \x01(\t2\xa6\x02\n\x08RaftNode\x12\x42\n\x0bRequestVote\x12\x18.raft.RequestVoteRequest\x1a\x19.raft.RequestVoteResponse\x12H\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x1b.raft.AppendEntriesResponse\x12H\n\rClientRequest\x12\x1a.raft.ClientRequestMessage\x1a\x1b.raft.ClientResponseMessage\x12\x42\n\rGetLeaderInfo\x12\x17.raft.LeaderInfoRequest\x1a\x18.raft.LeaderInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTVOTEREQUEST']._serialized_start=20
  _globals['_REQUESTVOTEREQUEST']._serialized_end=118
  _globals['_REQUESTVOTERESPONSE']._serialized_start=120
  _globals['_REQUESTVOTERESPONSE']._serialized_end=176
  _globals['_APPENDENTRIESREQUEST']._serialized_start=179
  _globals['_APPENDENTRIESREQUEST']._serialized_end=331
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=333
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=387
  _globals['_LOGENTRY']._serialized_start=389
  _globals['_LOGENTRY']._serialized_end=447
  _globals['_CLIENTREQUESTMESSAGE']._serialized_start=449
  _globals['_CLIENTREQUESTMESSAGE']._serialized_end=490
  _globals['_CLIENTRESPONSEMESSAGE']._serialized_start=492
  _globals['_CLIENTRESPONSEMESSAGE']._serialized_end=548
  _globals['_LEADERINFOREQUEST']._serialized_start=550
  _globals['_LEADERINFOREQUEST']._serialized_end=569
  _globals['_LEADERINFORESPONSE']._serialized_start=571
  _globals['_LEADERINFORESPONSE']._serialized_end=632
  _globals['_RAFTNODE']._serialized_start=635
  _globals['_RAFTNODE']._serialized_end=929
# @@protoc_insertion_point(module_scope)
